backend:
  name: git-gateway
  branch: master
media_folder: 'static/img/'
public_folder: 'img'
collections:
  - name: "posts"
    label: "Posts"
    label_singular: Post
    folder: 'content/en/post'
    path: '{{slug}}/index'
    create: true  # Allow users to create new documents in this collection
    fields:  # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Subtitle", name: "subtitle", widget: "string", required: false}
      - {label: "Summary", name: "summary", widget: "markdown", required: false}
      - label: "Draft"
        name: "draft"
        required: false
        widget: "boolean"
        default: false 
      - label: "Featured"
        name: "featured"
        required: false
        widget: "boolean"
        default: false
      # - label: "Authors"
      #   name: "authors"
      #   required: false
      #   widget: "list"
      - label: "Tags"
        name: "tags"
        required: false
        widget: "list"
      - label: "Categories"
        name: "categories"
        required: false
        widget: "list"
      # - label: "Projects"
      #   name: "projects"
      #   required: false
      #   widget: "list"
      - label: "Featured Image"
        name: "featured image"
        required: false
        widget: object
        fields:
          - label: "Upload an image named `featured.jpg/png`"
            name: "filename"
            widget: "image"
            default: "featured"
            required: false
            media_library:
              config:
                multiple: false
          - {label: Caption, name: caption, widget: string, required: false}
          - {label: "Where's the focal point in the image? Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight.", name: focal_point, widget: string, required: false, default: "Smart"}
          - {label: Thumbnail Only?, name: preview_only, widget: boolean, required: false, default: false}
      - {label: "Body", name: "body", widget: "markdown"}
 
  - name: "publications"
    label: "Publications"
    label_singular: Publications
    folder: 'content/en/publication'
    path: '{{slug}}/index'
    create: true  # Allow users to create new documents in this collection
    fields:  # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Publication Type", name: "publication_types", widget: "number"}
      - {label: "Publication", name: "publication", widget: "string"}
      - {label: "Abstract", name: "abstract", widget: "string"}
   
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/privacy.md"
        label: "Privacy Policy"
        name: "privacy"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Publish Date", name: "date", widget: "datetime"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
          - {label: "Summary", name: "summary", widget: "markdown"}
          - label: "Draft"
            name: "draft"
            required: false
            widget: "boolean"
            default: false
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "content/terms.md"
        label: "Terms"
        name: "terms"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Publish Date", name: "date", widget: "datetime"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
          - {label: "Summary", name: "summary", widget: "markdown"}
          - label: "Draft"
            name: "draft"
            required: false
            widget: "boolean"
            default: false
          - {label: "Body", name: "body", widget: "markdown"}
